# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runFleXScan <- function(setting, case_mat, coord_mat, adj_mat) {
    .Call('_rflexscan_runFleXScan', PACKAGE = 'rflexscan', setting, case_mat, coord_mat, adj_mat)
}

